baseURL: 'https://teoivancevic.github.io'
languageCode: 'en-us'
title: 'Teo Ivancevic'
theme: 'PaperMod'


menu:
    main:
        - name: About
          url: about
        - name: Now
          url: now


params:
    homeInfoParams:
        Title: Teo Ivancevic
        Content: Hello, I'm Teo Ivancevic...
    
    assets:
        favicon: "/favicon.ico"
        favicon16x16:  "/favicon-16x16.png"
        favicon32x32:  "/favicon-32x32.png"
        apple_touch_icon:  "/apple-touch-icon.png"
        safari_pinned_tab:  "/safari-pinned-tab.svg"

    socialIcons: # optional
        - name: github
          url: "https://github.com/teoivancevic"
        - name: linkedin
          url: "https://www.linkedin.com/in/teo-ivan%C4%8Devi%C4%87-b5803a221/"
