baseURL: "https://teoivancevic.github.io"
languageCode: "en-us"
title: "Teo Ivančević"
theme: "PaperMod"

menu:
  main:
    - name: Home
      url: /
      weight: 1
    # - name: About
    #   url: about
    #   weight: 2
    - name: Now
      url: now
      weight: 3
    - name: Blog
      url: https://teoivancevic.substack.com
      weight: 4
    - name: Contact
      url: contact
      weight: 5

params:
  profileMode:
    enabled: true
    title: "Welcome! " # optional default will be site title
    subtitle: "I'm **Teo Ivančević**, third year CS student at FER in **Zagreb, Croatia.**"
    imageUrl: "/profile pix.jpeg"
    imageTitle: "Teo Ivančević" # optional
    imageWidth: 200 # custom size
    imageHeight: 200 # custom size
    # buttons:
    #   - name: Now
    #     url: "/now"
    #   - name: Github
    #     url: "https://github.com/teoivancevic"
  # homeInfoParams:
  #     Title: Teo Ivancevic
  #     Content: Hello, I'm Teo Ivancevic...

  homeInfoParams:
    enabled: false
    title: TEO TITLE
    imageUrl: "/profile pix.jpeg"

  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"

  socialIcons: # optional
    - name: linkedin
      url: "https://www.linkedin.com/in/teoivancevic/"
    - name: github
      url: "https://github.com/teoivancevic"
    
